name: Checks

on: [push, pull_request]

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup latest deno version
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Run deno fmt
        run: deno fmt --check src/

      - name: Run deno lint
        run: deno lint --unstable src/

  Build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup latest deno version
      uses: denolib/setup-deno@v2
      with:
        deno-version: v1.x

    - run: npm ci
    - run: npm run build --if-present